apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-depo-tommy
  labels:
    app: god
spec:
  replicas: 2
  selector:
    matchLabels:
      app: god
  template:
    metadata:
      labels:
        app: god
    spec:
      containers:
        - name: tom-cont
          image: dockerworm21/random-repo:new-tom-std-ui
          ports:
          - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: god
  name: my-svc-tommy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: god
status:
  loadBalancer: {}
